Add pretty summary

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -51,3 +51,20 @@ jobs:
       tags: |
         ${{ needs.setup.outputs.latest }}
 
+  summary:
+    runs-on: ubuntu-latest
+    needs: [build-image]
+    if: success() || failure()
+    steps:
+      - name: "Generate summary"
+        run: |
+          {
+            echo '# Subscription Cleanup Job'
+            # if build-image was successful
+            if [ "${{ needs.build-image.result }}" == "success" ]; then
+              printf '\n\n## Image\n'
+              printf '\n```json\n'
+              echo '${{ needs.build-image.outputs.images }}' | jq
+              printf '\n```\n'
+            fi
+          } >> $GITHUB_STEP_SUMMARY
